/*  Auto generated by mk.eastasian.lisp  */
#ifndef __EASTASIAN_UNICODE_HEADER__
#define __EASTASIAN_UNICODE_HEADER__

#include "define.h"
#include "typedef.h"

#define EastAsianTable_Size 1137

enum EastAsianType {
#ifdef LISP_DEBUG
    EastAsian_Debug = 10,
#endif
    EastAsian_error,
    EastAsian_N,
    EastAsian_A,
    EastAsian_H,
    EastAsian_W,
    EastAsian_F,
    EastAsian_NA,
    EastAsian_Size
};

struct eastasian_struct {
    unicode a, b;
    enum EastAsianType c;
};

#define EastAsianSymbol _n(EastAsianSymbol)
#define EastAsianAscii _n(EastAsianAscii)
#define EastAsianTable _n(EastAsianTable)
#define eastasian_symbol _n(eastasian_symbol)
#define eastasian_width _n(eastasian_width)
#define init_eastasian _n(init_eastasian)
extern unsigned EastAsianSymbol[EastAsian_Size];
extern const enum EastAsianType EastAsianAscii[0x80];
extern const struct eastasian_struct EastAsianTable[EastAsianTable_Size];
enum EastAsianType eastasian_symbol(unicode c);
unsigned eastasian_width(unicode c);
void init_eastasian(void);

#endif

