/*  Auto generated by mk.eastasian.lisp  */
#ifndef __EASTASIAN_UNICODE_HEADER__
#define __EASTASIAN_UNICODE_HEADER__

#include "define.h"
#include "typedef.h"

#define EastAsianTable_Size 1137

enum EastAsianType {
#ifdef LISP_DEBUG
    EastAsian_Debug = 10,
#endif
    EastAsian_error,
    EastAsian_N,
    EastAsian_A,
    EastAsian_H,
    EastAsian_W,
    EastAsian_F,
    EastAsian_NA,
    EastAsian_Size
};

struct eastasian_struct {
    unicode a, b;
    enum EastAsianType c;
};

__extern unsigned EastAsianSymbol[EastAsian_Size];
__extern const enum EastAsianType EastAsianAscii[0x80];
__extern const struct eastasian_struct EastAsianTable[EastAsianTable_Size];
_g enum EastAsianType eastasian_symbol(unicode c);
_g unsigned eastasian_width(unicode c);
_g void init_eastasian(void);

#endif

