#define LISP_PACKAGE_COUNT_CLOS 128
#define LISP_PACKAGE_COUNT_CODE 106
#define LISP_PACKAGE_COUNT_COMMON 962
#define LISP_PACKAGE_COUNT_KEYWORD 191
#define LISP_PACKAGE_COUNT_RT 10
#define LISP_PACKAGE_COUNT_SYSTEM 223
