#define LISP_PACKAGE_COUNT_CLOS 135
#define LISP_PACKAGE_COUNT_CODE 119
#define LISP_PACKAGE_COUNT_COMMON 963
#define LISP_PACKAGE_COUNT_KEYWORD 231
#define LISP_PACKAGE_COUNT_RT 11
#define LISP_PACKAGE_COUNT_SYSTEM 345
