#define LISP_PACKAGE_COUNT_CLOS 52
#define LISP_PACKAGE_COUNT_CODE 106
#define LISP_PACKAGE_COUNT_COMMON 961
#define LISP_PACKAGE_COUNT_KEYWORD 164
#define LISP_PACKAGE_COUNT_RT 9
#define LISP_PACKAGE_COUNT_SYSTEM 222
