/*
 *  npt -- ANSI Common Lisp Programming Language.
 *    https://github.com/nptcl/npt
 *    https://github.com/nptcl/npt-amalgamation
 *
 *  File: lispdl.c
 */
#ifdef __clang__
#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wunused-function"
#endif
#ifdef __GNUC__
#pragma GCC diagnostic push
#pragma GCC diagnostic ignored "-Wunused-function"
#endif

#ifdef __cplusplus
#ifndef __STDC_LIMIT_MACROS
#define __STDC_LIMIT_MACROS
#endif
#ifndef __STDC_CONSTANT_MACROS
#define __STDC_CONSTANT_MACROS
#endif
#endif

#include "lispdl.h"
#include <stdint.h>

/*
 *  variables
 */
addr lisp_nil_object;
addr lisp_t_object;

/* extern_type.h */
int (*lisp_hold_p)(addr x);
void (*lisp_hold_value)(addr x, addr *ret);
void (*lisp_hold_set)(addr x, addr value);
addr (*Lisp_holdv)(addr x);
void (*lisp_hold)(addr *ret, addr value);
addr (*Lisp_hold)(void);
void (*lisp0_nil)(addr *ret);
void (*lisp0_t)(addr *ret);
void (*lisp_nil)(addr x);
void (*lisp_t)(addr x);
addr (*Lisp_nil)(void);
addr (*Lisp_t)(void);
int (*lisp_nil_p)(addr x);
int (*lisp_t_p)(addr x);
int (*lisp_null_p)(addr x);
int (*lisp_character_p)(addr x);
int (*lisp_cons_p)(addr x);
int (*lisp_list_p)(addr x);
int (*lisp_string_p)(addr x);
int (*lisp_strvect_p)(addr x);
int (*lisp_symbol_p)(addr x);
int (*lisp_array_p)(addr x);
int (*lisp_vector_p)(addr x);
int (*lisp_fixnum_p)(addr x);
int (*lisp_bignum_p)(addr x);
int (*lisp_integer_p)(addr x);
int (*lisp_ratio_p)(addr x);
int (*lisp_rational_p)(addr x);
int (*lisp_single_float_p)(addr x);
int (*lisp_double_float_p)(addr x);
int (*lisp_long_float_p)(addr x);
int (*lisp_float_p)(addr x);
int (*lisp_real_p)(addr x);
int (*lisp_complex_p)(addr x);
int (*lisp_number_p)(addr x);
int (*lisp_clos_p)(addr x);
int (*lisp_hashtable_p)(addr x);
int (*lisp_readtable_p)(addr x);
int (*lisp_control_p)(addr x);
int (*lisp_callname_p)(addr x);
int (*lisp_function_p)(addr x);
int (*lisp_package_p)(addr x);
int (*lisp_random_state_p)(addr x);
int (*lisp_pathname_p)(addr x);
int (*lisp_stream_p)(addr x);
int (*lisp_restart_p)(addr x);
int (*lisp_environment_p)(addr x);
int (*lisp_bitvector_p)(addr x);
int (*lisp_print_dispatch_p)(addr x);
int (*lisp_paper_p)(addr x);

/* extern_sequence.h */
void (*lisp0_cons)(addr *ret, addr car, addr cdr);
void (*lisp_cons)(addr x, addr car, addr cdr);
void (*lisp0_vector)(addr *ret, size_t size);
void (*lisp_vector)(addr x, size_t size);
void (*lisp0_list_va)(addr *ret, va_list args);
void (*lisp0_lista_va)(addr *ret, va_list args);
void (*lisp0_list)(addr *ret, ...);
void (*lisp_list)(addr x, ...);
void (*lisp0_lista)(addr *ret, ...);
void (*lisp_lista)(addr x, ...);
int (*lisp0_getelt_)(addr *ret, addr pos, size_t index);
int (*lisp_getelt_)(addr x, addr pos, size_t index);
int (*lisp_setelt_)(addr pos, size_t index, addr value);
int (*lisp_length_)(addr pos, size_t *ret);
int (*lisp0_reverse_)(addr *ret, addr pos);
int (*lisp0_nreverse_)(addr *ret, addr pos);
int (*lisp_reverse_)(addr x, addr pos);
int (*lisp_nreverse_)(addr x, addr pos);
void (*lisp0_car)(addr *ret, addr list);
void (*lisp0_cdr)(addr *ret, addr list);
void (*lisp0_carcdr)(addr *car, addr *cdr, addr list);
void (*lisp_car)(addr x, addr list);
void (*lisp_cdr)(addr x, addr list);
void (*lisp_carcdr)(addr x, addr y, addr list);
void (*lisp_setf_car)(addr cons, addr value);
void (*lisp_setf_cdr)(addr cons, addr value);
void (*lisp_setf_carcdr)(addr cons, addr car, addr cdr);
int (*lisp0_string8_)(addr *ret, const void *str);
int (*lisp0_string16_)(addr *ret, const void *str);
int (*lisp0_string32_)(addr *ret, const void *str);
int (*lisp_string8_)(addr x, const void *str);
int (*lisp_string16_)(addr x, const void *str);
int (*lisp_string32_)(addr x, const void *str);
int (*lisp_string_getc_)(addr pos, size_t i, unicode *c);
int (*lisp_strvect_getc)(addr pos, size_t i, unicode *c);
int (*lisp_strvect_length)(addr pos, size_t *ret);

/* extern_object.h */
int (*lisp0_character_)(addr *ret, unicode value);
void (*lisp0_fixnum)(addr *ret, fixnum value);
int (*lisp0_float_)(addr *ret, float value);
int (*lisp0_double_)(addr *ret, double value);
int (*lisp0_long_double_)(addr *ret, long double value);
int (*lisp_character_)(addr x, unicode value);
void (*lisp_fixnum)(addr x, fixnum value);
int (*lisp_float_)(addr x, float value);
int (*lisp_double_)(addr x, double value);
int (*lisp_long_double_)(addr x, long double value);
int (*lisp_zero_p)(addr value);
int (*lisp_plus_p)(addr value);
int (*lisp_minus_p)(addr value);
void (*lisp_get_character)(addr pos, unicode *ret);
void (*lisp_get_fixnum)(addr pos, fixnum *ret);
int (*lisp_get_float_)(addr pos, float *ret);
int (*lisp_get_double_)(addr pos, double *ret);
int (*lisp_get_long_double_)(addr pos, long double *ret);
int (*lisp0_package_)(addr *ret, addr pos);
int (*lisp0_package8_)(addr *ret, const void *str);
int (*lisp0_package16_)(addr *ret, const void *str);
int (*lisp0_package32_)(addr *ret, const void *str);
int (*lisp_package_)(addr x, addr pos);
int (*lisp_package8_)(addr x, const void *str);
int (*lisp_package16_)(addr x, const void *str);
int (*lisp_package32_)(addr x, const void *str);
int (*lisp_in_package_)(addr pos);
int (*lisp_in_package8_)(const void *str);
int (*lisp_in_package16_)(const void *str);
int (*lisp_in_package32_)(const void *str);
int (*lisp_push_and_in_package_)(addr pos);
int (*lisp_push_and_in_package8_)(const void *str);
int (*lisp_push_and_in_package16_)(const void *str);
int (*lisp_push_and_in_package32_)(const void *str);
int (*lisp0_intern_)(addr *ret, addr package, addr name);
int (*lisp0_intern8_)(addr *ret, const void *package, const void *name);
int (*lisp0_intern16_)(addr *ret, const void *package, const void *name);
int (*lisp0_intern32_)(addr *ret, const void *package, const void *name);
int (*lisp_intern_)(addr x, addr package, addr name);
int (*lisp_intern8_)(addr x, const void *package, const void *name);
int (*lisp_intern16_)(addr x, const void *package, const void *name);
int (*lisp_intern32_)(addr x, const void *package, const void *name);
int (*lisp0_reader_)(addr *ret, addr str);
int (*lisp0_reader8_)(addr *ret, const void *str);
int (*lisp0_reader16_)(addr *ret, const void *str);
int (*lisp0_reader32_)(addr *ret, const void *str);
int (*lisp_reader_)(addr x, addr str);
int (*lisp_reader8_)(addr x, const void *str);
int (*lisp_reader16_)(addr x, const void *str);
int (*lisp_reader32_)(addr x, const void *str);
int (*lisp0_pathname_)(addr *ret, addr name);
int (*lisp0_pathname8_)(addr *ret, const void *str);
int (*lisp0_pathname16_)(addr *ret, const void *str);
int (*lisp0_pathname32_)(addr *ret, const void *str);
int (*lisp0_namestring_)(addr *ret, addr path);
int (*lisp_pathname_)(addr x, addr name);
int (*lisp_pathname8_)(addr x, const void *str);
int (*lisp_pathname16_)(addr x, const void *str);
int (*lisp_pathname32_)(addr x, const void *str);
int (*lisp_namestring_)(addr x, addr path);
int (*lisp0_paper_)(addr *ret, size_t array, size_t body);
int (*lisp_paper_)(addr x, size_t array, size_t body);
int (*lisp_paper_gettype_)(addr x, byte *ret);
int (*lisp_paper_settype_)(addr x, byte value);
int (*lisp_paper_lenarray_)(addr x, size_t *ret);
int (*lisp_paper_lenbody_)(addr x, size_t *ret);
int (*lisp0_paper_getarray_)(addr *ret, addr pos, size_t index);
int (*lisp_paper_getarray_)(addr x, addr pos, size_t index);
int (*lisp_paper_setarray_)(addr x, size_t index, addr value);
int (*lisp_paper_getbody_)(addr x, size_t index, byte *ret);
int (*lisp_paper_setbody_)(addr x, size_t index, byte value);
int (*lisp_paper_getmemory_)(addr x, size_t a, size_t b, void *output, size_t *ret);
int (*lisp_paper_setmemory_)(addr x, size_t a, size_t b, const void *input, size_t *ret);
int (*lisp_paper_body_unsafe_)(addr x, byte **ptr, size_t *ret);

/* extern_init.h */
FILE *(*lisperror_stream)(void);
int (*lisperror_noeol)(const char *fmt, ...);
int (*lisperror_va)(const char *fmt, va_list args);
int (*lisperror)(const char *fmt, ...);

/* extern_execute.h */
int (*lisp0_eval_)(addr *ret, addr pos);
int (*lisp0_eval8_)(addr *ret, const void *str);
int (*lisp0_eval16_)(addr *ret, const void *str);
int (*lisp0_eval32_)(addr *ret, const void *str);
int (*lisp_eval_)(addr x, addr pos);
int (*lisp_eval8_)(addr x, const void *str);
int (*lisp_eval16_)(addr x, const void *str);
int (*lisp_eval32_)(addr x, const void *str);
int (*lisp0_call_)(addr *ret, addr call, addr args);
int (*lisp_call_)(addr x, addr call, addr args);
int (*lisp0_funcall_)(addr *ret, addr call, ...);
int (*lisp0_funcall8_)(addr *ret, const void *str, ...);
int (*lisp0_funcall16_)(addr *ret, const void *str, ...);
int (*lisp0_funcall32_)(addr *ret, const void *str, ...);
int (*lisp_funcall_)(addr x, addr call, ...);
int (*lisp_funcall8_)(addr x, const void *str, ...);
int (*lisp_funcall16_)(addr x, const void *str, ...);
int (*lisp_funcall32_)(addr x, const void *str, ...);
int (*lisp0_apply_)(addr *ret, addr call, ...);
int (*lisp0_apply8_)(addr *ret, const void *str, ...);
int (*lisp0_apply16_)(addr *ret, const void *str, ...);
int (*lisp0_apply32_)(addr *ret, const void *str, ...);
int (*lisp_apply_)(addr x, addr call, ...);
int (*lisp_apply8_)(addr x, const void *str, ...);
int (*lisp_apply16_)(addr x, const void *str, ...);
int (*lisp_apply32_)(addr x, const void *str, ...);
int (*lisp_eval_control_)(addr eval);
int (*lisp_eval_string_control_)(addr eval);
int (*lisp_call_control_)(addr call, addr args);
int (*lisp_funcall_control_)(addr call, ...);
int (*lisp_apply_control_)(addr call, ...);
void (*lisp0_result_control)(addr *ret);
void (*lisp0_result2_control)(addr *ret1, addr *ret2);
void (*lisp0_values_control)(addr *ret);
void (*lisp0_nth_value_control)(addr *ret, size_t index);
void (*lisp_result_control)(addr x);
void (*lisp_result2_control)(addr x, addr y);
void (*lisp_values_control)(addr x);
void (*lisp_nth_value_control)(addr x, size_t index);
void (*lisp_set_result_control)(addr value);
void (*lisp_set_values_control)(addr first, ...);
void (*lisp_set_values_nil_control)(void);
void (*lisp_set_values_list_control)(addr list);
int (*lisp_equal_control)(addr control);
int (*lisp_break_control)(void);
int (*lisp_escape_control)(void);
void (*lisp_reset_control)(void);
enum lisp_escape (*lisp_escape_type_control)(void);
void (*lisp_save_control)(addr *ret);
void (*lisp_rollback_control)(addr value);
int (*lisp_eval_loop_)(void);

/* extern_control.h */
void (*lisp_push_control)(addr *ret);
int (*lisp_pop_control_)(addr control);
int (*lisp_push_special_)(addr symbol, addr value);
int (*lisp_push_special8_)(const void *name, addr value);
int (*lisp_push_special16_)(const void *name, addr value);
int (*lisp_push_special32_)(const void *name, addr value);
int (*lisp0_get_special_)(addr *ret, addr symbol);
int (*lisp0_get_special8_)(addr *ret, const void *name);
int (*lisp0_get_special16_)(addr *ret, const void *name);
int (*lisp0_get_special32_)(addr *ret, const void *name);
int (*lisp_get_special_)(addr x, addr symbol);
int (*lisp_get_special8_)(addr x, const void *name);
int (*lisp_get_special16_)(addr x, const void *name);
int (*lisp_get_special32_)(addr x, const void *name);
int (*lisp_set_special_)(addr symbol, addr value);
int (*lisp_set_special8_)(const void *name, addr value);
int (*lisp_set_special16_)(const void *name, addr value);
int (*lisp_set_special32_)(const void *name, addr value);
int (*lisp_defvar_)(addr symbol);
int (*lisp_defvar8_)(const void *str);
int (*lisp_defvar16_)(const void *str);
int (*lisp_defvar32_)(const void *str);
void (*lisp_catch)(addr symbol);
int (*lisp_throw_)(addr symbol);
int (*lisp_handler_bind_)(addr name, addr call);
int (*lisp_handler_case_)(addr name, addr call);
void (*lisp_handler_reverse)(void);
void (*lisp0_restart_make)(addr *ret, addr name, addr call, int casep);
void (*lisp_restart_make)(addr x, addr name, addr call, int casep);
void (*lisp_restart_interactive)(addr restart, addr call);
void (*lisp_restart_report)(addr restart, addr call);
void (*lisp_restart_test)(addr restart, addr call);
void (*lisp_restart_push)(addr restart);
void (*lisp_restart_reverse)(void);

/* extern_error.h */
void (*lisp_abort)(void);
void (*lisp_abortf)(const char *fmt, ...);
void (*lisp_abort8)(const void *fmt, ...);
void (*lisp_abort16)(const void *fmt, ...);
void (*lisp_abort32)(const void *fmt, ...);
lisp_abort_calltype (*lisp_set_abort_handler)(lisp_abort_calltype call);
lisp_abort_calltype (*lisp_set_abort_setjmp_handler)(void);
int (*lisp_signal_)(addr condition);
int (*lisp_error_)(addr condition);
int (*lisp_error8_)(const void *str, ...);
int (*lisp_error16_)(const void *str, ...);
int (*lisp_error32_)(const void *str, ...);
int (*lisp_warn8_)(const void *str, ...);
int (*lisp_warn16_)(const void *str, ...);
int (*lisp_warn32_)(const void *str, ...);

/* extern_function.h */
void (*lisp0_get_function)(addr *ret, addr symbol);
void (*lisp0_get_setf)(addr *ret, addr symbol);
void (*lisp_get_function)(addr x, addr symbol);
void (*lisp_get_setf)(addr x, addr symbol);
int (*lisp0_get_function_)(addr *ret, addr value);
int (*lisp0_get_function8_)(addr *ret, const void *str);
int (*lisp0_get_function16_)(addr *ret, const void *str);
int (*lisp0_get_function32_)(addr *ret, const void *str);
int (*lisp_get_function_)(addr x, addr value);
int (*lisp_get_function8_)(addr x, const void *str);
int (*lisp_get_function16_)(addr x, const void *str);
int (*lisp_get_function32_)(addr x, const void *str);
int (*lisp0_get_setf_)(addr *ret, addr value);
int (*lisp0_get_setf8_)(addr *ret, const void *str);
int (*lisp0_get_setf16_)(addr *ret, const void *str);
int (*lisp0_get_setf32_)(addr *ret, const void *str);
int (*lisp_get_setf_)(addr x, addr value);
int (*lisp_get_setf8_)(addr x, const void *str);
int (*lisp_get_setf16_)(addr x, const void *str);
int (*lisp_get_setf32_)(addr x, const void *str);
void (*lisp_compiled_macro)(int index, lisp_calltype_macro call);
void (*lisp_compiled_rest)(int index, lisp_calltype_rest call);
void (*lisp_compiled_dynamic)(int index, lisp_calltype_dynamic call);
void (*lisp_compiled_any)(int index, lisp_calltype_any call);
void (*lisp_compiled_empty)(int index, lisp_calltype_empty call);
void (*lisp_compiled_var1)(int index, lisp_calltype_var1 call);
void (*lisp_compiled_var2)(int index, lisp_calltype_var2 call);
void (*lisp_compiled_var3)(int index, lisp_calltype_var3 call);
void (*lisp_compiled_var4)(int index, lisp_calltype_var4 call);
void (*lisp_compiled_var5)(int index, lisp_calltype_var5 call);
void (*lisp_compiled_var6)(int index, lisp_calltype_var6 call);
void (*lisp_compiled_opt1)(int index, lisp_calltype_opt1 call);
void (*lisp_compiled_opt2)(int index, lisp_calltype_opt2 call);
void (*lisp_compiled_opt3)(int index, lisp_calltype_opt3 call);
void (*lisp_compiled_var1opt1)(int index, lisp_calltype_var1opt1 call);
void (*lisp_compiled_var1opt2)(int index, lisp_calltype_var1opt2 call);
void (*lisp_compiled_var1opt3)(int index, lisp_calltype_var1opt3 call);
void (*lisp_compiled_var2opt1)(int index, lisp_calltype_var2opt1 call);
void (*lisp_compiled_var2opt2)(int index, lisp_calltype_var2opt2 call);
void (*lisp_compiled_var2opt3)(int index, lisp_calltype_var2opt3 call);
void (*lisp_compiled_var3opt1)(int index, lisp_calltype_var3opt1 call);
void (*lisp_compiled_var3opt2)(int index, lisp_calltype_var3opt2 call);
void (*lisp_compiled_var3opt3)(int index, lisp_calltype_var3opt3 call);
void (*lisp_compiled_var1rest)(int index, lisp_calltype_var1rest call);
void (*lisp_compiled_var2rest)(int index, lisp_calltype_var2rest call);
void (*lisp_compiled_var3rest)(int index, lisp_calltype_var3rest call);
void (*lisp_compiled_var1dynamic)(int index, lisp_calltype_var1dynamic call);
void (*lisp_compiled_var2dynamic)(int index, lisp_calltype_var2dynamic call);
void (*lisp_compiled_var3dynamic)(int index, lisp_calltype_var3dynamic call);
int (*lisp0_compiled_function_)(addr *ret, int index, addr symbol);
int (*lisp0_compiled_function8_)(addr *ret, int index, const void *str);
int (*lisp0_compiled_function16_)(addr *ret, int index, const void *str);
int (*lisp0_compiled_function32_)(addr *ret, int index, const void *str);
int (*lisp_compiled_function_)(addr x, int index, addr symbol);
int (*lisp_compiled_function8_)(addr x, int index, const void *str);
int (*lisp_compiled_function16_)(addr x, int index, const void *str);
int (*lisp_compiled_function32_)(addr x, int index, const void *str);
int (*lisp_compiled_defun_)(int index, addr symbol);
int (*lisp_compiled_defun8_)(int index, const void *str);
int (*lisp_compiled_defun16_)(int index, const void *str);
int (*lisp_compiled_defun32_)(int index, const void *str);
int (*lisp_compiled_defun_setf_)(int index, addr symbol);
int (*lisp_compiled_defun_setf8_)(int index, const void *str);
int (*lisp_compiled_defun_setf16_)(int index, const void *str);
int (*lisp_compiled_defun_setf32_)(int index, const void *str);
void (*lisp_compiled_setvalue)(addr pos, addr value);
void (*lisp_compiled_getvalue)(addr *ret);

/* extern_instance.h */
void (*lisp0_find_class)(addr *ret, addr symbol);
int (*lisp0_find_class_)(addr *ret, addr symbol);
int (*lisp0_find_class8_)(addr *ret, const void *str);
int (*lisp0_find_class16_)(addr *ret, const void *str);
int (*lisp0_find_class32_)(addr *ret, const void *str);
void (*lisp_find_class)(addr x, addr symbol);
int (*lisp_find_class_)(addr x, addr symbol);
int (*lisp_find_class8_)(addr x, const void *str);
int (*lisp_find_class16_)(addr x, const void *str);
int (*lisp_find_class32_)(addr x, const void *str);
int (*lisp0_instance_)(addr *ret, addr clos, ...);
int (*lisp0_instance8_)(addr *ret, const void *clos, ...);
int (*lisp0_instance16_)(addr *ret, const void *clos, ...);
int (*lisp0_instance32_)(addr *ret, const void *clos, ...);
int (*lisp_instance_)(addr x, addr clos, ...);
int (*lisp_instance8_)(addr x, const void *clos, ...);
int (*lisp_instance16_)(addr x, const void *clos, ...);
int (*lisp_instance32_)(addr x, const void *clos, ...);
int (*lisp_slot_exists_)(addr instance, addr symbol, int *ret);
int (*lisp_slot_exists8_)(addr instance, const void *str, int *ret);
int (*lisp_slot_exists16_)(addr instance, const void *str, int *ret);
int (*lisp_slot_exists32_)(addr instance, const void *str, int *ret);
int (*lisp_slot_boundp_)(addr instance, addr symbol, int *ret);
int (*lisp_slot_boundp8_)(addr instance, const void *str, int *ret);
int (*lisp_slot_boundp16_)(addr instance, const void *str, int *ret);
int (*lisp_slot_boundp32_)(addr instance, const void *str, int *ret);
int (*lisp_slot_makunbound_)(addr instance, addr symbol);
int (*lisp_slot_makunbound8_)(addr instance, const void *str);
int (*lisp_slot_makunbound16_)(addr instance, const void *str);
int (*lisp_slot_makunbound32_)(addr instance, const void *str);
int (*lisp0_slot_value_)(addr *ret, addr instance, addr symbol);
int (*lisp0_slot_value8_)(addr *ret, addr instance, const void *str);
int (*lisp0_slot_value16_)(addr *ret, addr instance, const void *str);
int (*lisp0_slot_value32_)(addr *ret, addr instance, const void *str);
int (*lisp_slot_value_)(addr x, addr instance, addr symbol);
int (*lisp_slot_value8_)(addr x, addr instance, const void *str);
int (*lisp_slot_value16_)(addr x, addr instance, const void *str);
int (*lisp_slot_value32_)(addr x, addr instance, const void *str);
int (*lisp_slot_setf_)(addr instance, addr symbol, addr value);
int (*lisp_slot_setf8_)(addr instance, const void *str, addr value);
int (*lisp_slot_setf16_)(addr instance, const void *str, addr value);
int (*lisp_slot_setf32_)(addr instance, const void *str, addr value);

/* extern_print.h */
int (*lisp_format8_)(addr stream, const void *str, ...);
int (*lisp_format16_)(addr stream, const void *str, ...);
int (*lisp_format32_)(addr stream, const void *str, ...);
int (*lisp_stdout8_)(const void *str, ...);
int (*lisp_stdout16_)(const void *str, ...);
int (*lisp_stdout32_)(const void *str, ...);
int (*lisp_stderr8_)(const void *str, ...);
int (*lisp_stderr16_)(const void *str, ...);
int (*lisp_stderr32_)(const void *str, ...);
int (*lisp0_stringf8_)(addr *ret, const void *str, ...);
int (*lisp0_stringf16_)(addr *ret, const void *str, ...);
int (*lisp0_stringf32_)(addr *ret, const void *str, ...);
int (*lisp_stringf8_)(addr x, const void *str, ...);
int (*lisp_stringf16_)(addr x, const void *str, ...);
int (*lisp_stringf32_)(addr x, const void *str, ...);

/* extern_stream.h */
void (*lisp0_stream_define)(addr *ret, int index, size_t size);
void (*lisp_stream_define)(addr x, int index, size_t size);
void (*lisp_stream_memory)(addr stream, void **ret);
void (*lisp0_getinfo_stream)(addr *ret, addr stream);
void (*lisp_getinfo_stream)(addr x, addr stream);
void (*lisp_setinfo_stream)(addr stream, addr value);
void (*lisp_stream_calltype_close)(int, lisp_streamtype_close);
void (*lisp_stream_calltype_read_byte)(int, lisp_streamtype_read_byte);
void (*lisp_stream_calltype_unread_byte)(int, lisp_streamtype_unread_byte);
void (*lisp_stream_calltype_write_byte)(int, lisp_streamtype_write_byte);
void (*lisp_stream_calltype_read_char)(int, lisp_streamtype_read_char);
void (*lisp_stream_calltype_read_hang)(int, lisp_streamtype_read_hang);
void (*lisp_stream_calltype_unread_char)(int, lisp_streamtype_unread_char);
void (*lisp_stream_calltype_write_char)(int, lisp_streamtype_write_char);
void (*lisp_stream_calltype_getleft)(int, lisp_streamtype_getleft);
void (*lisp_stream_calltype_setleft)(int, lisp_streamtype_setleft);
void (*lisp_stream_calltype_inputp)(int, lisp_streamtype_inputp);
void (*lisp_stream_calltype_outputp)(int, lisp_streamtype_outputp);
void (*lisp_stream_calltype_interactivep)(int, lisp_streamtype_interactivep);
void (*lisp_stream_calltype_characterp)(int, lisp_streamtype_characterp);
void (*lisp_stream_calltype_binaryp)(int, lisp_streamtype_binaryp);
void (*lisp_stream_calltype_element_type)(int, lisp_streamtype_element_type);
void (*lisp_stream_calltype_external_format)(int, lisp_streamtype_external_format);
void (*lisp_stream_calltype_file_length)(int, lisp_streamtype_file_length);
void (*lisp_stream_calltype_file_position)(int, lisp_streamtype_file_position);
void (*lisp_stream_calltype_file_position_start)(int, lisp_streamtype_file_position_start);
void (*lisp_stream_calltype_file_position_end)(int, lisp_streamtype_file_position_end);
void (*lisp_stream_calltype_file_position_set)(int, lisp_streamtype_file_position_set);
void (*lisp_stream_calltype_file_charlen)(int, lisp_streamtype_file_charlen);
void (*lisp_stream_calltype_file_strlen)(int, lisp_streamtype_file_strlen);
void (*lisp_stream_calltype_listen)(int, lisp_streamtype_listen);
void (*lisp_stream_calltype_clear_input)(int, lisp_streamtype_clear_input);
void (*lisp_stream_calltype_finish_output)(int, lisp_streamtype_finish_output);
void (*lisp_stream_calltype_force_output)(int, lisp_streamtype_force_output);
void (*lisp_stream_calltype_clear_output)(int, lisp_streamtype_clear_output);
void (*lisp_stream_calltype_exitpoint)(int, lisp_streamtype_exitpoint);
void (*lisp_stream_calltype_termsize)(int, lisp_streamtype_termsize);
void (*lisp_stream_calltype_error_close)(int);
void (*lisp_stream_calltype_error_read_byte)(int);
void (*lisp_stream_calltype_error_unread_byte)(int);
void (*lisp_stream_calltype_error_write_byte)(int);
void (*lisp_stream_calltype_error_read_char)(int);
void (*lisp_stream_calltype_error_read_hang)(int);
void (*lisp_stream_calltype_error_unread_char)(int);
void (*lisp_stream_calltype_error_write_char)(int);
void (*lisp_stream_calltype_error_getleft)(int);
void (*lisp_stream_calltype_error_setleft)(int);
void (*lisp_stream_calltype_error_inputp)(int);
void (*lisp_stream_calltype_error_outputp)(int);
void (*lisp_stream_calltype_error_interactivep)(int);
void (*lisp_stream_calltype_error_characterp)(int);
void (*lisp_stream_calltype_error_binaryp)(int);
void (*lisp_stream_calltype_error_element_type)(int);
void (*lisp_stream_calltype_error_external_format)(int);
void (*lisp_stream_calltype_error_file_length)(int);
void (*lisp_stream_calltype_error_file_position)(int);
void (*lisp_stream_calltype_error_file_position_start)(int);
void (*lisp_stream_calltype_error_file_position_end)(int);
void (*lisp_stream_calltype_error_file_position_set)(int);
void (*lisp_stream_calltype_error_file_charlen)(int);
void (*lisp_stream_calltype_error_file_strlen)(int);
void (*lisp_stream_calltype_error_listen)(int);
void (*lisp_stream_calltype_error_clear_input)(int);
void (*lisp_stream_calltype_error_finish_output)(int);
void (*lisp_stream_calltype_error_force_output)(int);
void (*lisp_stream_calltype_error_clear_output)(int);
void (*lisp_stream_calltype_error_exitpoint)(int);
void (*lisp_stream_calltype_error_termsize)(int);

/* extern_unicode.h */
int (*lisp_eastasian_set)(enum LispEastAsianType type, unsigned width);
int (*lisp_eastasian_get)(enum LispEastAsianType type, unsigned *ret);
enum LispEastAsianType (*lisp_eastasian_type_unicode)(unicode c);
enum LispEastAsianType (*lisp_eastasian_type_character)(addr value);
unsigned (*lisp_eastasian_unicode)(unicode c);
int (*lisp_eastasian_character_)(addr value, unsigned *ret);
int (*lisp_eastasian_string_)(addr value, size_t *ret);
int (*lisp_eastasian_width_)(addr value, size_t *ret);
int (*lisp_unicode_count)(void);
int (*lisp_utf8_encode)(unicode c, void *ptr, size_t *ret);
int (*lisp_utf16_range)(unicode c);
int (*lisp_utf16_high)(unicode c);
int (*lisp_utf16_low)(unicode c);
unicode (*lisp_utf16_merge)(byte16 first, byte16 second);


/*
 * lisp_dlfiles
 */
#define LispdlLet(ptr, x, type) (x = (type)ptr[lispdl_##x])
int lisp_dlfile_update(lisp_dlfile_array ptr)
{
    if (ptr[lispdl_unbound] != (addr)(~(intptr_t)0))
        return 1;
    if (ptr[lispdl_end] != NULL)
        return 1;

    /* variables */
    lisp_nil_object = (addr)ptr[lispdl_nil];
    lisp_t_object = (addr)ptr[lispdl_t];

    /* extern_type.h */
    LispdlLet(ptr, lisp_hold_p, int (*)(addr x));
    LispdlLet(ptr, lisp_hold_value, void (*)(addr x, addr *ret));
    LispdlLet(ptr, lisp_hold_set, void (*)(addr x, addr value));
    LispdlLet(ptr, Lisp_holdv, addr (*)(addr x));
    LispdlLet(ptr, lisp_hold, void (*)(addr *ret, addr value));
    LispdlLet(ptr, Lisp_hold, addr (*)(void));
    LispdlLet(ptr, lisp0_nil, void (*)(addr *ret));
    LispdlLet(ptr, lisp0_t, void (*)(addr *ret));
    LispdlLet(ptr, lisp_nil, void (*)(addr x));
    LispdlLet(ptr, lisp_t, void (*)(addr x));
    LispdlLet(ptr, Lisp_nil, addr (*)(void));
    LispdlLet(ptr, Lisp_t, addr (*)(void));
    LispdlLet(ptr, lisp_nil_p, int (*)(addr x));
    LispdlLet(ptr, lisp_t_p, int (*)(addr x));
    LispdlLet(ptr, lisp_null_p, int (*)(addr x));
    LispdlLet(ptr, lisp_character_p, int (*)(addr x));
    LispdlLet(ptr, lisp_cons_p, int (*)(addr x));
    LispdlLet(ptr, lisp_list_p, int (*)(addr x));
    LispdlLet(ptr, lisp_string_p, int (*)(addr x));
    LispdlLet(ptr, lisp_strvect_p, int (*)(addr x));
    LispdlLet(ptr, lisp_symbol_p, int (*)(addr x));
    LispdlLet(ptr, lisp_array_p, int (*)(addr x));
    LispdlLet(ptr, lisp_vector_p, int (*)(addr x));
    LispdlLet(ptr, lisp_fixnum_p, int (*)(addr x));
    LispdlLet(ptr, lisp_bignum_p, int (*)(addr x));
    LispdlLet(ptr, lisp_integer_p, int (*)(addr x));
    LispdlLet(ptr, lisp_ratio_p, int (*)(addr x));
    LispdlLet(ptr, lisp_rational_p, int (*)(addr x));
    LispdlLet(ptr, lisp_single_float_p, int (*)(addr x));
    LispdlLet(ptr, lisp_double_float_p, int (*)(addr x));
    LispdlLet(ptr, lisp_long_float_p, int (*)(addr x));
    LispdlLet(ptr, lisp_float_p, int (*)(addr x));
    LispdlLet(ptr, lisp_real_p, int (*)(addr x));
    LispdlLet(ptr, lisp_complex_p, int (*)(addr x));
    LispdlLet(ptr, lisp_number_p, int (*)(addr x));
    LispdlLet(ptr, lisp_clos_p, int (*)(addr x));
    LispdlLet(ptr, lisp_hashtable_p, int (*)(addr x));
    LispdlLet(ptr, lisp_readtable_p, int (*)(addr x));
    LispdlLet(ptr, lisp_control_p, int (*)(addr x));
    LispdlLet(ptr, lisp_callname_p, int (*)(addr x));
    LispdlLet(ptr, lisp_function_p, int (*)(addr x));
    LispdlLet(ptr, lisp_package_p, int (*)(addr x));
    LispdlLet(ptr, lisp_random_state_p, int (*)(addr x));
    LispdlLet(ptr, lisp_pathname_p, int (*)(addr x));
    LispdlLet(ptr, lisp_stream_p, int (*)(addr x));
    LispdlLet(ptr, lisp_restart_p, int (*)(addr x));
    LispdlLet(ptr, lisp_environment_p, int (*)(addr x));
    LispdlLet(ptr, lisp_bitvector_p, int (*)(addr x));
    LispdlLet(ptr, lisp_print_dispatch_p, int (*)(addr x));
    LispdlLet(ptr, lisp_paper_p, int (*)(addr x));

    /* extern_sequence.h */
    LispdlLet(ptr, lisp0_cons, void (*)(addr *ret, addr car, addr cdr));
    LispdlLet(ptr, lisp_cons, void (*)(addr x, addr car, addr cdr));
    LispdlLet(ptr, lisp0_vector, void (*)(addr *ret, size_t size));
    LispdlLet(ptr, lisp_vector, void (*)(addr x, size_t size));
    LispdlLet(ptr, lisp0_list_va, void (*)(addr *ret, va_list args));
    LispdlLet(ptr, lisp0_lista_va, void (*)(addr *ret, va_list args));
    LispdlLet(ptr, lisp0_list, void (*)(addr *ret, ...));
    LispdlLet(ptr, lisp_list, void (*)(addr x, ...));
    LispdlLet(ptr, lisp0_lista, void (*)(addr *ret, ...));
    LispdlLet(ptr, lisp_lista, void (*)(addr x, ...));
    LispdlLet(ptr, lisp0_getelt_, int (*)(addr *ret, addr pos, size_t index));
    LispdlLet(ptr, lisp_getelt_, int (*)(addr x, addr pos, size_t index));
    LispdlLet(ptr, lisp_setelt_, int (*)(addr pos, size_t index, addr value));
    LispdlLet(ptr, lisp_length_, int (*)(addr pos, size_t *ret));
    LispdlLet(ptr, lisp0_reverse_, int (*)(addr *ret, addr pos));
    LispdlLet(ptr, lisp0_nreverse_, int (*)(addr *ret, addr pos));
    LispdlLet(ptr, lisp_reverse_, int (*)(addr x, addr pos));
    LispdlLet(ptr, lisp_nreverse_, int (*)(addr x, addr pos));
    LispdlLet(ptr, lisp0_car, void (*)(addr *ret, addr list));
    LispdlLet(ptr, lisp0_cdr, void (*)(addr *ret, addr list));
    LispdlLet(ptr, lisp0_carcdr, void (*)(addr *car, addr *cdr, addr list));
    LispdlLet(ptr, lisp_car, void (*)(addr x, addr list));
    LispdlLet(ptr, lisp_cdr, void (*)(addr x, addr list));
    LispdlLet(ptr, lisp_carcdr, void (*)(addr x, addr y, addr list));
    LispdlLet(ptr, lisp_setf_car, void (*)(addr cons, addr value));
    LispdlLet(ptr, lisp_setf_cdr, void (*)(addr cons, addr value));
    LispdlLet(ptr, lisp_setf_carcdr, void (*)(addr cons, addr car, addr cdr));
    LispdlLet(ptr, lisp0_string8_, int (*)(addr *ret, const void *str));
    LispdlLet(ptr, lisp0_string16_, int (*)(addr *ret, const void *str));
    LispdlLet(ptr, lisp0_string32_, int (*)(addr *ret, const void *str));
    LispdlLet(ptr, lisp_string8_, int (*)(addr x, const void *str));
    LispdlLet(ptr, lisp_string16_, int (*)(addr x, const void *str));
    LispdlLet(ptr, lisp_string32_, int (*)(addr x, const void *str));
    LispdlLet(ptr, lisp_string_getc_, int (*)(addr pos, size_t i, unicode *c));
    LispdlLet(ptr, lisp_strvect_getc, int (*)(addr pos, size_t i, unicode *c));
    LispdlLet(ptr, lisp_strvect_length, int (*)(addr pos, size_t *ret));

    /* extern_object.h */
    LispdlLet(ptr, lisp0_character_, int (*)(addr *ret, unicode value));
    LispdlLet(ptr, lisp0_fixnum, void (*)(addr *ret, fixnum value));
    LispdlLet(ptr, lisp0_float_, int (*)(addr *ret, float value));
    LispdlLet(ptr, lisp0_double_, int (*)(addr *ret, double value));
    LispdlLet(ptr, lisp0_long_double_, int (*)(addr *ret, long double value));
    LispdlLet(ptr, lisp_character_, int (*)(addr x, unicode value));
    LispdlLet(ptr, lisp_fixnum, void (*)(addr x, fixnum value));
    LispdlLet(ptr, lisp_float_, int (*)(addr x, float value));
    LispdlLet(ptr, lisp_double_, int (*)(addr x, double value));
    LispdlLet(ptr, lisp_long_double_, int (*)(addr x, long double value));
    LispdlLet(ptr, lisp_zero_p, int (*)(addr value));
    LispdlLet(ptr, lisp_plus_p, int (*)(addr value));
    LispdlLet(ptr, lisp_minus_p, int (*)(addr value));
    LispdlLet(ptr, lisp_get_character, void (*)(addr pos, unicode *ret));
    LispdlLet(ptr, lisp_get_fixnum, void (*)(addr pos, fixnum *ret));
    LispdlLet(ptr, lisp_get_float_, int (*)(addr pos, float *ret));
    LispdlLet(ptr, lisp_get_double_, int (*)(addr pos, double *ret));
    LispdlLet(ptr, lisp_get_long_double_, int (*)(addr pos, long double *ret));
    LispdlLet(ptr, lisp0_package_, int (*)(addr *ret, addr pos));
    LispdlLet(ptr, lisp0_package8_, int (*)(addr *ret, const void *str));
    LispdlLet(ptr, lisp0_package16_, int (*)(addr *ret, const void *str));
    LispdlLet(ptr, lisp0_package32_, int (*)(addr *ret, const void *str));
    LispdlLet(ptr, lisp_package_, int (*)(addr x, addr pos));
    LispdlLet(ptr, lisp_package8_, int (*)(addr x, const void *str));
    LispdlLet(ptr, lisp_package16_, int (*)(addr x, const void *str));
    LispdlLet(ptr, lisp_package32_, int (*)(addr x, const void *str));
    LispdlLet(ptr, lisp_in_package_, int (*)(addr pos));
    LispdlLet(ptr, lisp_in_package8_, int (*)(const void *str));
    LispdlLet(ptr, lisp_in_package16_, int (*)(const void *str));
    LispdlLet(ptr, lisp_in_package32_, int (*)(const void *str));
    LispdlLet(ptr, lisp_push_and_in_package_, int (*)(addr pos));
    LispdlLet(ptr, lisp_push_and_in_package8_, int (*)(const void *str));
    LispdlLet(ptr, lisp_push_and_in_package16_, int (*)(const void *str));
    LispdlLet(ptr, lisp_push_and_in_package32_, int (*)(const void *str));
    LispdlLet(ptr, lisp0_intern_, int (*)(addr *ret, addr package, addr name));
    LispdlLet(ptr, lisp0_intern8_, int (*)(addr *ret, const void *package, const void *name));
    LispdlLet(ptr, lisp0_intern16_, int (*)(addr *ret, const void *package, const void *name));
    LispdlLet(ptr, lisp0_intern32_, int (*)(addr *ret, const void *package, const void *name));
    LispdlLet(ptr, lisp_intern_, int (*)(addr x, addr package, addr name));
    LispdlLet(ptr, lisp_intern8_, int (*)(addr x, const void *package, const void *name));
    LispdlLet(ptr, lisp_intern16_, int (*)(addr x, const void *package, const void *name));
    LispdlLet(ptr, lisp_intern32_, int (*)(addr x, const void *package, const void *name));
    LispdlLet(ptr, lisp0_reader_, int (*)(addr *ret, addr str));
    LispdlLet(ptr, lisp0_reader8_, int (*)(addr *ret, const void *str));
    LispdlLet(ptr, lisp0_reader16_, int (*)(addr *ret, const void *str));
    LispdlLet(ptr, lisp0_reader32_, int (*)(addr *ret, const void *str));
    LispdlLet(ptr, lisp_reader_, int (*)(addr x, addr str));
    LispdlLet(ptr, lisp_reader8_, int (*)(addr x, const void *str));
    LispdlLet(ptr, lisp_reader16_, int (*)(addr x, const void *str));
    LispdlLet(ptr, lisp_reader32_, int (*)(addr x, const void *str));
    LispdlLet(ptr, lisp0_pathname_, int (*)(addr *ret, addr name));
    LispdlLet(ptr, lisp0_pathname8_, int (*)(addr *ret, const void *str));
    LispdlLet(ptr, lisp0_pathname16_, int (*)(addr *ret, const void *str));
    LispdlLet(ptr, lisp0_pathname32_, int (*)(addr *ret, const void *str));
    LispdlLet(ptr, lisp0_namestring_, int (*)(addr *ret, addr path));
    LispdlLet(ptr, lisp_pathname_, int (*)(addr x, addr name));
    LispdlLet(ptr, lisp_pathname8_, int (*)(addr x, const void *str));
    LispdlLet(ptr, lisp_pathname16_, int (*)(addr x, const void *str));
    LispdlLet(ptr, lisp_pathname32_, int (*)(addr x, const void *str));
    LispdlLet(ptr, lisp_namestring_, int (*)(addr x, addr path));
    LispdlLet(ptr, lisp0_paper_, int (*)(addr *ret, size_t array, size_t body));
    LispdlLet(ptr, lisp_paper_, int (*)(addr x, size_t array, size_t body));
    LispdlLet(ptr, lisp_paper_gettype_, int (*)(addr x, byte *ret));
    LispdlLet(ptr, lisp_paper_settype_, int (*)(addr x, byte value));
    LispdlLet(ptr, lisp_paper_lenarray_, int (*)(addr x, size_t *ret));
    LispdlLet(ptr, lisp_paper_lenbody_, int (*)(addr x, size_t *ret));
    LispdlLet(ptr, lisp0_paper_getarray_, int (*)(addr *ret, addr pos, size_t index));
    LispdlLet(ptr, lisp_paper_getarray_, int (*)(addr x, addr pos, size_t index));
    LispdlLet(ptr, lisp_paper_setarray_, int (*)(addr x, size_t index, addr value));
    LispdlLet(ptr, lisp_paper_getbody_, int (*)(addr x, size_t index, byte *ret));
    LispdlLet(ptr, lisp_paper_setbody_, int (*)(addr x, size_t index, byte value));
    LispdlLet(ptr, lisp_paper_getmemory_, int (*)(addr x, size_t a, size_t b, void *output, size_t *ret));
    LispdlLet(ptr, lisp_paper_setmemory_, int (*)(addr x, size_t a, size_t b, const void *input, size_t *ret));
    LispdlLet(ptr, lisp_paper_body_unsafe_, int (*)(addr x, byte **ptr, size_t *ret));

    /* extern_init.h */
    LispdlLet(ptr, lisperror_stream, FILE *(*)(void));
    LispdlLet(ptr, lisperror_noeol, int (*)(const char *fmt, ...));
    LispdlLet(ptr, lisperror_va, int (*)(const char *fmt, va_list args));
    LispdlLet(ptr, lisperror, int (*)(const char *fmt, ...));

    /* extern_execute.h */
    LispdlLet(ptr, lisp0_eval_, int (*)(addr *ret, addr pos));
    LispdlLet(ptr, lisp0_eval8_, int (*)(addr *ret, const void *str));
    LispdlLet(ptr, lisp0_eval16_, int (*)(addr *ret, const void *str));
    LispdlLet(ptr, lisp0_eval32_, int (*)(addr *ret, const void *str));
    LispdlLet(ptr, lisp_eval_, int (*)(addr x, addr pos));
    LispdlLet(ptr, lisp_eval8_, int (*)(addr x, const void *str));
    LispdlLet(ptr, lisp_eval16_, int (*)(addr x, const void *str));
    LispdlLet(ptr, lisp_eval32_, int (*)(addr x, const void *str));
    LispdlLet(ptr, lisp0_call_, int (*)(addr *ret, addr call, addr args));
    LispdlLet(ptr, lisp_call_, int (*)(addr x, addr call, addr args));
    LispdlLet(ptr, lisp0_funcall_, int (*)(addr *ret, addr call, ...));
    LispdlLet(ptr, lisp0_funcall8_, int (*)(addr *ret, const void *str, ...));
    LispdlLet(ptr, lisp0_funcall16_, int (*)(addr *ret, const void *str, ...));
    LispdlLet(ptr, lisp0_funcall32_, int (*)(addr *ret, const void *str, ...));
    LispdlLet(ptr, lisp_funcall_, int (*)(addr x, addr call, ...));
    LispdlLet(ptr, lisp_funcall8_, int (*)(addr x, const void *str, ...));
    LispdlLet(ptr, lisp_funcall16_, int (*)(addr x, const void *str, ...));
    LispdlLet(ptr, lisp_funcall32_, int (*)(addr x, const void *str, ...));
    LispdlLet(ptr, lisp0_apply_, int (*)(addr *ret, addr call, ...));
    LispdlLet(ptr, lisp0_apply8_, int (*)(addr *ret, const void *str, ...));
    LispdlLet(ptr, lisp0_apply16_, int (*)(addr *ret, const void *str, ...));
    LispdlLet(ptr, lisp0_apply32_, int (*)(addr *ret, const void *str, ...));
    LispdlLet(ptr, lisp_apply_, int (*)(addr x, addr call, ...));
    LispdlLet(ptr, lisp_apply8_, int (*)(addr x, const void *str, ...));
    LispdlLet(ptr, lisp_apply16_, int (*)(addr x, const void *str, ...));
    LispdlLet(ptr, lisp_apply32_, int (*)(addr x, const void *str, ...));
    LispdlLet(ptr, lisp_eval_control_, int (*)(addr eval));
    LispdlLet(ptr, lisp_eval_string_control_, int (*)(addr eval));
    LispdlLet(ptr, lisp_call_control_, int (*)(addr call, addr args));
    LispdlLet(ptr, lisp_funcall_control_, int (*)(addr call, ...));
    LispdlLet(ptr, lisp_apply_control_, int (*)(addr call, ...));
    LispdlLet(ptr, lisp0_result_control, void (*)(addr *ret));
    LispdlLet(ptr, lisp0_result2_control, void (*)(addr *ret1, addr *ret2));
    LispdlLet(ptr, lisp0_values_control, void (*)(addr *ret));
    LispdlLet(ptr, lisp0_nth_value_control, void (*)(addr *ret, size_t index));
    LispdlLet(ptr, lisp_result_control, void (*)(addr x));
    LispdlLet(ptr, lisp_result2_control, void (*)(addr x, addr y));
    LispdlLet(ptr, lisp_values_control, void (*)(addr x));
    LispdlLet(ptr, lisp_nth_value_control, void (*)(addr x, size_t index));
    LispdlLet(ptr, lisp_set_result_control, void (*)(addr value));
    LispdlLet(ptr, lisp_set_values_control, void (*)(addr first, ...));
    LispdlLet(ptr, lisp_set_values_nil_control, void (*)(void));
    LispdlLet(ptr, lisp_set_values_list_control, void (*)(addr list));
    LispdlLet(ptr, lisp_equal_control, int (*)(addr control));
    LispdlLet(ptr, lisp_break_control, int (*)(void));
    LispdlLet(ptr, lisp_escape_control, int (*)(void));
    LispdlLet(ptr, lisp_reset_control, void (*)(void));
    LispdlLet(ptr, lisp_escape_type_control, enum lisp_escape (*)(void));
    LispdlLet(ptr, lisp_save_control, void (*)(addr *ret));
    LispdlLet(ptr, lisp_rollback_control, void (*)(addr value));
    LispdlLet(ptr, lisp_eval_loop_, int (*)(void));

    /* extern_control.h */
    LispdlLet(ptr, lisp_push_control, void (*)(addr *ret));
    LispdlLet(ptr, lisp_pop_control_, int (*)(addr control));
    LispdlLet(ptr, lisp_push_special_, int (*)(addr symbol, addr value));
    LispdlLet(ptr, lisp_push_special8_, int (*)(const void *name, addr value));
    LispdlLet(ptr, lisp_push_special16_, int (*)(const void *name, addr value));
    LispdlLet(ptr, lisp_push_special32_, int (*)(const void *name, addr value));
    LispdlLet(ptr, lisp0_get_special_, int (*)(addr *ret, addr symbol));
    LispdlLet(ptr, lisp0_get_special8_, int (*)(addr *ret, const void *name));
    LispdlLet(ptr, lisp0_get_special16_, int (*)(addr *ret, const void *name));
    LispdlLet(ptr, lisp0_get_special32_, int (*)(addr *ret, const void *name));
    LispdlLet(ptr, lisp_get_special_, int (*)(addr x, addr symbol));
    LispdlLet(ptr, lisp_get_special8_, int (*)(addr x, const void *name));
    LispdlLet(ptr, lisp_get_special16_, int (*)(addr x, const void *name));
    LispdlLet(ptr, lisp_get_special32_, int (*)(addr x, const void *name));
    LispdlLet(ptr, lisp_set_special_, int (*)(addr symbol, addr value));
    LispdlLet(ptr, lisp_set_special8_, int (*)(const void *name, addr value));
    LispdlLet(ptr, lisp_set_special16_, int (*)(const void *name, addr value));
    LispdlLet(ptr, lisp_set_special32_, int (*)(const void *name, addr value));
    LispdlLet(ptr, lisp_defvar_, int (*)(addr symbol));
    LispdlLet(ptr, lisp_defvar8_, int (*)(const void *str));
    LispdlLet(ptr, lisp_defvar16_, int (*)(const void *str));
    LispdlLet(ptr, lisp_defvar32_, int (*)(const void *str));
    LispdlLet(ptr, lisp_catch, void (*)(addr symbol));
    LispdlLet(ptr, lisp_throw_, int (*)(addr symbol));
    LispdlLet(ptr, lisp_handler_bind_, int (*)(addr name, addr call));
    LispdlLet(ptr, lisp_handler_case_, int (*)(addr name, addr call));
    LispdlLet(ptr, lisp_handler_reverse, void (*)(void));
    LispdlLet(ptr, lisp0_restart_make, void (*)(addr *ret, addr name, addr call, int casep));
    LispdlLet(ptr, lisp_restart_make, void (*)(addr x, addr name, addr call, int casep));
    LispdlLet(ptr, lisp_restart_interactive, void (*)(addr restart, addr call));
    LispdlLet(ptr, lisp_restart_report, void (*)(addr restart, addr call));
    LispdlLet(ptr, lisp_restart_test, void (*)(addr restart, addr call));
    LispdlLet(ptr, lisp_restart_push, void (*)(addr restart));
    LispdlLet(ptr, lisp_restart_reverse, void (*)(void));

    /* extern_error.h */
    LispdlLet(ptr, lisp_abort, void (*)(void));
    LispdlLet(ptr, lisp_abortf, void (*)(const char *fmt, ...));
    LispdlLet(ptr, lisp_abort8, void (*)(const void *fmt, ...));
    LispdlLet(ptr, lisp_abort16, void (*)(const void *fmt, ...));
    LispdlLet(ptr, lisp_abort32, void (*)(const void *fmt, ...));
    LispdlLet(ptr, lisp_set_abort_handler, lisp_abort_calltype (*)(lisp_abort_calltype call));
    LispdlLet(ptr, lisp_set_abort_setjmp_handler, lisp_abort_calltype (*)(void));
    LispdlLet(ptr, lisp_signal_, int (*)(addr condition));
    LispdlLet(ptr, lisp_error_, int (*)(addr condition));
    LispdlLet(ptr, lisp_error8_, int (*)(const void *str, ...));
    LispdlLet(ptr, lisp_error16_, int (*)(const void *str, ...));
    LispdlLet(ptr, lisp_error32_, int (*)(const void *str, ...));
    LispdlLet(ptr, lisp_warn8_, int (*)(const void *str, ...));
    LispdlLet(ptr, lisp_warn16_, int (*)(const void *str, ...));
    LispdlLet(ptr, lisp_warn32_, int (*)(const void *str, ...));

    /* extern_function.h */
    LispdlLet(ptr, lisp0_get_function, void (*)(addr *ret, addr symbol));
    LispdlLet(ptr, lisp0_get_setf, void (*)(addr *ret, addr symbol));
    LispdlLet(ptr, lisp_get_function, void (*)(addr x, addr symbol));
    LispdlLet(ptr, lisp_get_setf, void (*)(addr x, addr symbol));
    LispdlLet(ptr, lisp0_get_function_, int (*)(addr *ret, addr value));
    LispdlLet(ptr, lisp0_get_function8_, int (*)(addr *ret, const void *str));
    LispdlLet(ptr, lisp0_get_function16_, int (*)(addr *ret, const void *str));
    LispdlLet(ptr, lisp0_get_function32_, int (*)(addr *ret, const void *str));
    LispdlLet(ptr, lisp_get_function_, int (*)(addr x, addr value));
    LispdlLet(ptr, lisp_get_function8_, int (*)(addr x, const void *str));
    LispdlLet(ptr, lisp_get_function16_, int (*)(addr x, const void *str));
    LispdlLet(ptr, lisp_get_function32_, int (*)(addr x, const void *str));
    LispdlLet(ptr, lisp0_get_setf_, int (*)(addr *ret, addr value));
    LispdlLet(ptr, lisp0_get_setf8_, int (*)(addr *ret, const void *str));
    LispdlLet(ptr, lisp0_get_setf16_, int (*)(addr *ret, const void *str));
    LispdlLet(ptr, lisp0_get_setf32_, int (*)(addr *ret, const void *str));
    LispdlLet(ptr, lisp_get_setf_, int (*)(addr x, addr value));
    LispdlLet(ptr, lisp_get_setf8_, int (*)(addr x, const void *str));
    LispdlLet(ptr, lisp_get_setf16_, int (*)(addr x, const void *str));
    LispdlLet(ptr, lisp_get_setf32_, int (*)(addr x, const void *str));
    LispdlLet(ptr, lisp_compiled_macro, void (*)(int index, lisp_calltype_macro call));
    LispdlLet(ptr, lisp_compiled_rest, void (*)(int index, lisp_calltype_rest call));
    LispdlLet(ptr, lisp_compiled_dynamic, void (*)(int index, lisp_calltype_dynamic call));
    LispdlLet(ptr, lisp_compiled_any, void (*)(int index, lisp_calltype_any call));
    LispdlLet(ptr, lisp_compiled_empty, void (*)(int index, lisp_calltype_empty call));
    LispdlLet(ptr, lisp_compiled_var1, void (*)(int index, lisp_calltype_var1 call));
    LispdlLet(ptr, lisp_compiled_var2, void (*)(int index, lisp_calltype_var2 call));
    LispdlLet(ptr, lisp_compiled_var3, void (*)(int index, lisp_calltype_var3 call));
    LispdlLet(ptr, lisp_compiled_var4, void (*)(int index, lisp_calltype_var4 call));
    LispdlLet(ptr, lisp_compiled_var5, void (*)(int index, lisp_calltype_var5 call));
    LispdlLet(ptr, lisp_compiled_var6, void (*)(int index, lisp_calltype_var6 call));
    LispdlLet(ptr, lisp_compiled_opt1, void (*)(int index, lisp_calltype_opt1 call));
    LispdlLet(ptr, lisp_compiled_opt2, void (*)(int index, lisp_calltype_opt2 call));
    LispdlLet(ptr, lisp_compiled_opt3, void (*)(int index, lisp_calltype_opt3 call));
    LispdlLet(ptr, lisp_compiled_var1opt1, void (*)(int index, lisp_calltype_var1opt1 call));
    LispdlLet(ptr, lisp_compiled_var1opt2, void (*)(int index, lisp_calltype_var1opt2 call));
    LispdlLet(ptr, lisp_compiled_var1opt3, void (*)(int index, lisp_calltype_var1opt3 call));
    LispdlLet(ptr, lisp_compiled_var2opt1, void (*)(int index, lisp_calltype_var2opt1 call));
    LispdlLet(ptr, lisp_compiled_var2opt2, void (*)(int index, lisp_calltype_var2opt2 call));
    LispdlLet(ptr, lisp_compiled_var2opt3, void (*)(int index, lisp_calltype_var2opt3 call));
    LispdlLet(ptr, lisp_compiled_var3opt1, void (*)(int index, lisp_calltype_var3opt1 call));
    LispdlLet(ptr, lisp_compiled_var3opt2, void (*)(int index, lisp_calltype_var3opt2 call));
    LispdlLet(ptr, lisp_compiled_var3opt3, void (*)(int index, lisp_calltype_var3opt3 call));
    LispdlLet(ptr, lisp_compiled_var1rest, void (*)(int index, lisp_calltype_var1rest call));
    LispdlLet(ptr, lisp_compiled_var2rest, void (*)(int index, lisp_calltype_var2rest call));
    LispdlLet(ptr, lisp_compiled_var3rest, void (*)(int index, lisp_calltype_var3rest call));
    LispdlLet(ptr, lisp_compiled_var1dynamic, void (*)(int index, lisp_calltype_var1dynamic call));
    LispdlLet(ptr, lisp_compiled_var2dynamic, void (*)(int index, lisp_calltype_var2dynamic call));
    LispdlLet(ptr, lisp_compiled_var3dynamic, void (*)(int index, lisp_calltype_var3dynamic call));
    LispdlLet(ptr, lisp0_compiled_function_, int (*)(addr *ret, int index, addr symbol));
    LispdlLet(ptr, lisp0_compiled_function8_, int (*)(addr *ret, int index, const void *str));
    LispdlLet(ptr, lisp0_compiled_function16_, int (*)(addr *ret, int index, const void *str));
    LispdlLet(ptr, lisp0_compiled_function32_, int (*)(addr *ret, int index, const void *str));
    LispdlLet(ptr, lisp_compiled_function_, int (*)(addr x, int index, addr symbol));
    LispdlLet(ptr, lisp_compiled_function8_, int (*)(addr x, int index, const void *str));
    LispdlLet(ptr, lisp_compiled_function16_, int (*)(addr x, int index, const void *str));
    LispdlLet(ptr, lisp_compiled_function32_, int (*)(addr x, int index, const void *str));
    LispdlLet(ptr, lisp_compiled_defun_, int (*)(int index, addr symbol));
    LispdlLet(ptr, lisp_compiled_defun8_, int (*)(int index, const void *str));
    LispdlLet(ptr, lisp_compiled_defun16_, int (*)(int index, const void *str));
    LispdlLet(ptr, lisp_compiled_defun32_, int (*)(int index, const void *str));
    LispdlLet(ptr, lisp_compiled_defun_setf_, int (*)(int index, addr symbol));
    LispdlLet(ptr, lisp_compiled_defun_setf8_, int (*)(int index, const void *str));
    LispdlLet(ptr, lisp_compiled_defun_setf16_, int (*)(int index, const void *str));
    LispdlLet(ptr, lisp_compiled_defun_setf32_, int (*)(int index, const void *str));
    LispdlLet(ptr, lisp_compiled_setvalue, void (*)(addr pos, addr value));
    LispdlLet(ptr, lisp_compiled_getvalue, void (*)(addr *ret));

    /* extern_instance.h */
    LispdlLet(ptr, lisp0_find_class, void (*)(addr *ret, addr symbol));
    LispdlLet(ptr, lisp0_find_class_, int (*)(addr *ret, addr symbol));
    LispdlLet(ptr, lisp0_find_class8_, int (*)(addr *ret, const void *str));
    LispdlLet(ptr, lisp0_find_class16_, int (*)(addr *ret, const void *str));
    LispdlLet(ptr, lisp0_find_class32_, int (*)(addr *ret, const void *str));
    LispdlLet(ptr, lisp_find_class, void (*)(addr x, addr symbol));
    LispdlLet(ptr, lisp_find_class_, int (*)(addr x, addr symbol));
    LispdlLet(ptr, lisp_find_class8_, int (*)(addr x, const void *str));
    LispdlLet(ptr, lisp_find_class16_, int (*)(addr x, const void *str));
    LispdlLet(ptr, lisp_find_class32_, int (*)(addr x, const void *str));
    LispdlLet(ptr, lisp0_instance_, int (*)(addr *ret, addr clos, ...));
    LispdlLet(ptr, lisp0_instance8_, int (*)(addr *ret, const void *clos, ...));
    LispdlLet(ptr, lisp0_instance16_, int (*)(addr *ret, const void *clos, ...));
    LispdlLet(ptr, lisp0_instance32_, int (*)(addr *ret, const void *clos, ...));
    LispdlLet(ptr, lisp_instance_, int (*)(addr x, addr clos, ...));
    LispdlLet(ptr, lisp_instance8_, int (*)(addr x, const void *clos, ...));
    LispdlLet(ptr, lisp_instance16_, int (*)(addr x, const void *clos, ...));
    LispdlLet(ptr, lisp_instance32_, int (*)(addr x, const void *clos, ...));
    LispdlLet(ptr, lisp_slot_exists_, int (*)(addr instance, addr symbol, int *ret));
    LispdlLet(ptr, lisp_slot_exists8_, int (*)(addr instance, const void *str, int *ret));
    LispdlLet(ptr, lisp_slot_exists16_, int (*)(addr instance, const void *str, int *ret));
    LispdlLet(ptr, lisp_slot_exists32_, int (*)(addr instance, const void *str, int *ret));
    LispdlLet(ptr, lisp_slot_boundp_, int (*)(addr instance, addr symbol, int *ret));
    LispdlLet(ptr, lisp_slot_boundp8_, int (*)(addr instance, const void *str, int *ret));
    LispdlLet(ptr, lisp_slot_boundp16_, int (*)(addr instance, const void *str, int *ret));
    LispdlLet(ptr, lisp_slot_boundp32_, int (*)(addr instance, const void *str, int *ret));
    LispdlLet(ptr, lisp_slot_makunbound_, int (*)(addr instance, addr symbol));
    LispdlLet(ptr, lisp_slot_makunbound8_, int (*)(addr instance, const void *str));
    LispdlLet(ptr, lisp_slot_makunbound16_, int (*)(addr instance, const void *str));
    LispdlLet(ptr, lisp_slot_makunbound32_, int (*)(addr instance, const void *str));
    LispdlLet(ptr, lisp0_slot_value_, int (*)(addr *ret, addr instance, addr symbol));
    LispdlLet(ptr, lisp0_slot_value8_, int (*)(addr *ret, addr instance, const void *str));
    LispdlLet(ptr, lisp0_slot_value16_, int (*)(addr *ret, addr instance, const void *str));
    LispdlLet(ptr, lisp0_slot_value32_, int (*)(addr *ret, addr instance, const void *str));
    LispdlLet(ptr, lisp_slot_value_, int (*)(addr x, addr instance, addr symbol));
    LispdlLet(ptr, lisp_slot_value8_, int (*)(addr x, addr instance, const void *str));
    LispdlLet(ptr, lisp_slot_value16_, int (*)(addr x, addr instance, const void *str));
    LispdlLet(ptr, lisp_slot_value32_, int (*)(addr x, addr instance, const void *str));
    LispdlLet(ptr, lisp_slot_setf_, int (*)(addr instance, addr symbol, addr value));
    LispdlLet(ptr, lisp_slot_setf8_, int (*)(addr instance, const void *str, addr value));
    LispdlLet(ptr, lisp_slot_setf16_, int (*)(addr instance, const void *str, addr value));
    LispdlLet(ptr, lisp_slot_setf32_, int (*)(addr instance, const void *str, addr value));

    /* extern_print.h */
    LispdlLet(ptr, lisp_format8_, int (*)(addr stream, const void *str, ...));
    LispdlLet(ptr, lisp_format16_, int (*)(addr stream, const void *str, ...));
    LispdlLet(ptr, lisp_format32_, int (*)(addr stream, const void *str, ...));
    LispdlLet(ptr, lisp_stdout8_, int (*)(const void *str, ...));
    LispdlLet(ptr, lisp_stdout16_, int (*)(const void *str, ...));
    LispdlLet(ptr, lisp_stdout32_, int (*)(const void *str, ...));
    LispdlLet(ptr, lisp_stderr8_, int (*)(const void *str, ...));
    LispdlLet(ptr, lisp_stderr16_, int (*)(const void *str, ...));
    LispdlLet(ptr, lisp_stderr32_, int (*)(const void *str, ...));
    LispdlLet(ptr, lisp0_stringf8_, int (*)(addr *ret, const void *str, ...));
    LispdlLet(ptr, lisp0_stringf16_, int (*)(addr *ret, const void *str, ...));
    LispdlLet(ptr, lisp0_stringf32_, int (*)(addr *ret, const void *str, ...));
    LispdlLet(ptr, lisp_stringf8_, int (*)(addr x, const void *str, ...));
    LispdlLet(ptr, lisp_stringf16_, int (*)(addr x, const void *str, ...));
    LispdlLet(ptr, lisp_stringf32_, int (*)(addr x, const void *str, ...));

    /* extern_stream.h */
    LispdlLet(ptr, lisp0_stream_define, void (*)(addr *ret, int index, size_t size));
    LispdlLet(ptr, lisp_stream_define, void (*)(addr x, int index, size_t size));
    LispdlLet(ptr, lisp_stream_memory, void (*)(addr stream, void **ret));
    LispdlLet(ptr, lisp0_getinfo_stream, void (*)(addr *ret, addr stream));
    LispdlLet(ptr, lisp_getinfo_stream, void (*)(addr x, addr stream));
    LispdlLet(ptr, lisp_setinfo_stream, void (*)(addr stream, addr value));
    LispdlLet(ptr, lisp_stream_calltype_close, void (*)(int, lisp_streamtype_close));
    LispdlLet(ptr, lisp_stream_calltype_read_byte, void (*)(int, lisp_streamtype_read_byte));
    LispdlLet(ptr, lisp_stream_calltype_unread_byte, void (*)(int, lisp_streamtype_unread_byte));
    LispdlLet(ptr, lisp_stream_calltype_write_byte, void (*)(int, lisp_streamtype_write_byte));
    LispdlLet(ptr, lisp_stream_calltype_read_char, void (*)(int, lisp_streamtype_read_char));
    LispdlLet(ptr, lisp_stream_calltype_read_hang, void (*)(int, lisp_streamtype_read_hang));
    LispdlLet(ptr, lisp_stream_calltype_unread_char, void (*)(int, lisp_streamtype_unread_char));
    LispdlLet(ptr, lisp_stream_calltype_write_char, void (*)(int, lisp_streamtype_write_char));
    LispdlLet(ptr, lisp_stream_calltype_getleft, void (*)(int, lisp_streamtype_getleft));
    LispdlLet(ptr, lisp_stream_calltype_setleft, void (*)(int, lisp_streamtype_setleft));
    LispdlLet(ptr, lisp_stream_calltype_inputp, void (*)(int, lisp_streamtype_inputp));
    LispdlLet(ptr, lisp_stream_calltype_outputp, void (*)(int, lisp_streamtype_outputp));
    LispdlLet(ptr, lisp_stream_calltype_interactivep, void (*)(int, lisp_streamtype_interactivep));
    LispdlLet(ptr, lisp_stream_calltype_characterp, void (*)(int, lisp_streamtype_characterp));
    LispdlLet(ptr, lisp_stream_calltype_binaryp, void (*)(int, lisp_streamtype_binaryp));
    LispdlLet(ptr, lisp_stream_calltype_element_type, void (*)(int, lisp_streamtype_element_type));
    LispdlLet(ptr, lisp_stream_calltype_external_format, void (*)(int, lisp_streamtype_external_format));
    LispdlLet(ptr, lisp_stream_calltype_file_length, void (*)(int, lisp_streamtype_file_length));
    LispdlLet(ptr, lisp_stream_calltype_file_position, void (*)(int, lisp_streamtype_file_position));
    LispdlLet(ptr, lisp_stream_calltype_file_position_start, void (*)(int, lisp_streamtype_file_position_start));
    LispdlLet(ptr, lisp_stream_calltype_file_position_end, void (*)(int, lisp_streamtype_file_position_end));
    LispdlLet(ptr, lisp_stream_calltype_file_position_set, void (*)(int, lisp_streamtype_file_position_set));
    LispdlLet(ptr, lisp_stream_calltype_file_charlen, void (*)(int, lisp_streamtype_file_charlen));
    LispdlLet(ptr, lisp_stream_calltype_file_strlen, void (*)(int, lisp_streamtype_file_strlen));
    LispdlLet(ptr, lisp_stream_calltype_listen, void (*)(int, lisp_streamtype_listen));
    LispdlLet(ptr, lisp_stream_calltype_clear_input, void (*)(int, lisp_streamtype_clear_input));
    LispdlLet(ptr, lisp_stream_calltype_finish_output, void (*)(int, lisp_streamtype_finish_output));
    LispdlLet(ptr, lisp_stream_calltype_force_output, void (*)(int, lisp_streamtype_force_output));
    LispdlLet(ptr, lisp_stream_calltype_clear_output, void (*)(int, lisp_streamtype_clear_output));
    LispdlLet(ptr, lisp_stream_calltype_exitpoint, void (*)(int, lisp_streamtype_exitpoint));
    LispdlLet(ptr, lisp_stream_calltype_termsize, void (*)(int, lisp_streamtype_termsize));
    LispdlLet(ptr, lisp_stream_calltype_error_close, void (*)(int));
    LispdlLet(ptr, lisp_stream_calltype_error_read_byte, void (*)(int));
    LispdlLet(ptr, lisp_stream_calltype_error_unread_byte, void (*)(int));
    LispdlLet(ptr, lisp_stream_calltype_error_write_byte, void (*)(int));
    LispdlLet(ptr, lisp_stream_calltype_error_read_char, void (*)(int));
    LispdlLet(ptr, lisp_stream_calltype_error_read_hang, void (*)(int));
    LispdlLet(ptr, lisp_stream_calltype_error_unread_char, void (*)(int));
    LispdlLet(ptr, lisp_stream_calltype_error_write_char, void (*)(int));
    LispdlLet(ptr, lisp_stream_calltype_error_getleft, void (*)(int));
    LispdlLet(ptr, lisp_stream_calltype_error_setleft, void (*)(int));
    LispdlLet(ptr, lisp_stream_calltype_error_inputp, void (*)(int));
    LispdlLet(ptr, lisp_stream_calltype_error_outputp, void (*)(int));
    LispdlLet(ptr, lisp_stream_calltype_error_interactivep, void (*)(int));
    LispdlLet(ptr, lisp_stream_calltype_error_characterp, void (*)(int));
    LispdlLet(ptr, lisp_stream_calltype_error_binaryp, void (*)(int));
    LispdlLet(ptr, lisp_stream_calltype_error_element_type, void (*)(int));
    LispdlLet(ptr, lisp_stream_calltype_error_external_format, void (*)(int));
    LispdlLet(ptr, lisp_stream_calltype_error_file_length, void (*)(int));
    LispdlLet(ptr, lisp_stream_calltype_error_file_position, void (*)(int));
    LispdlLet(ptr, lisp_stream_calltype_error_file_position_start, void (*)(int));
    LispdlLet(ptr, lisp_stream_calltype_error_file_position_end, void (*)(int));
    LispdlLet(ptr, lisp_stream_calltype_error_file_position_set, void (*)(int));
    LispdlLet(ptr, lisp_stream_calltype_error_file_charlen, void (*)(int));
    LispdlLet(ptr, lisp_stream_calltype_error_file_strlen, void (*)(int));
    LispdlLet(ptr, lisp_stream_calltype_error_listen, void (*)(int));
    LispdlLet(ptr, lisp_stream_calltype_error_clear_input, void (*)(int));
    LispdlLet(ptr, lisp_stream_calltype_error_finish_output, void (*)(int));
    LispdlLet(ptr, lisp_stream_calltype_error_force_output, void (*)(int));
    LispdlLet(ptr, lisp_stream_calltype_error_clear_output, void (*)(int));
    LispdlLet(ptr, lisp_stream_calltype_error_exitpoint, void (*)(int));
    LispdlLet(ptr, lisp_stream_calltype_error_termsize, void (*)(int));

    /* extern_unicode.h */
    LispdlLet(ptr, lisp_eastasian_set, int (*)(enum LispEastAsianType type, unsigned width));
    LispdlLet(ptr, lisp_eastasian_get, int (*)(enum LispEastAsianType type, unsigned *ret));
    LispdlLet(ptr, lisp_eastasian_type_unicode, enum LispEastAsianType (*)(unicode c));
    LispdlLet(ptr, lisp_eastasian_type_character, enum LispEastAsianType (*)(addr value));
    LispdlLet(ptr, lisp_eastasian_unicode, unsigned (*)(unicode c));
    LispdlLet(ptr, lisp_eastasian_character_, int (*)(addr value, unsigned *ret));
    LispdlLet(ptr, lisp_eastasian_string_, int (*)(addr value, size_t *ret));
    LispdlLet(ptr, lisp_eastasian_width_, int (*)(addr value, size_t *ret));
    LispdlLet(ptr, lisp_unicode_count, int (*)(void));
    LispdlLet(ptr, lisp_utf8_encode, int (*)(unicode c, void *ptr, size_t *ret));
    LispdlLet(ptr, lisp_utf16_range, int (*)(unicode c));
    LispdlLet(ptr, lisp_utf16_high, int (*)(unicode c));
    LispdlLet(ptr, lisp_utf16_low, int (*)(unicode c));
    LispdlLet(ptr, lisp_utf16_merge, unicode (*)(byte16 first, byte16 second));

    return 0;
}
#undef LispdlLet

#ifdef __GNUC__
#pragma GCC diagnostic pop
#endif
#ifdef __clang__
#pragma clang diagnostic pop
#endif
